project:
  type: website
  output-dir: _site

website:
  title: "jaydeblogs"
  navbar:
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Zaya"
        file: zaya.qmd
        
format:
  html:
    theme: pulse
    css: styles.css



