---
name: Jayde Homer
docname: "CV"
fontawesome: yes
address: "St. Louis, Missouri"
phone: "+1 315 952 1639"
email: "jaydehomer@wustl.edu"
www: "jaydehomer.github.io"
date: "`r format(Sys.time(), '%B %Y')`"
output: function(...) {source('homer_entries.R');vitae:::set_entry_formats(homer_entries);vitae::cv_document(..., template = "homertemplate.tex", citation_package = "biblatex")}
---

```{r setup, include=FALSE}
# To save log files
# rmarkdown::render("cv/homer_cv.Rmd", clean = FALSE)

knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)

library(tidyverse)
library(vitae)
library(lubridate)
library(glue)
library(rlang)
```

```{r loadData}
# Education
education <- data.table::fread("../data/education.csv",
                               encoding = "UTF-8") %>%
  as_tibble() %>%
  mutate(
    begin = as.Date(begin, format = "%m/%d/%y"),
    end = as.Date(end, format = "%m/%d/%y")
  )

# Job titles
job.titles <- data.table::fread("../data/job-titles.csv",
                                encoding = "UTF-8") %>%
  as_tibble() %>%
  mutate(
    begin = as.Date(begin, format = "%m/%d/%y"),
    end = as.Date(end, format = "%m/%d/%y")
  )

# Skills
skills <- data.table::fread("../data/skills.csv",
                            encoding = "UTF-8") %>%
  as_tibble()

# Job descriptions
job.descriptions <-
  data.table::fread("../data/job-descriptions.csv",
                    encoding = "UTF-8") %>%
  as_tibble()

# Awards
awards <- data.table::fread("../data/awards.csv",
                            encoding = "UTF-8") %>%
  as_tibble()

# Service descriptions
service.descriptions <-
  data.table::fread("../data/service-descriptions.csv",
                    encoding = "UTF-8") %>%
  as_tibble()

# Service titles
service.titles <- data.table::fread("../data/service-titles.csv",
                                encoding = "UTF-8") %>%
  as_tibble() %>%
  mutate(
    begin = as.Date(begin, format = "%m/%d/%y"),
    end = as.Date(end, format = "%m/%d/%y")
  )
```

# Data Analyst Skills

```{r}
skills_formatted <- skills |> 
  mutate(skill = if_else(is.na(details)|details=="", glue("{skill}"), glue("{skill} ({details})"))) |> 
  group_by(group) |> 
  summarize(skills = glue_collapse(skill, sep = " $\\bullet$ "))
```

```{r, results='asis', width = 40000}
for (group in skills_formatted$group) {
  cat(
    glue("\\textbf{<<tools::toTitleCase(group)>>}:", .open = "<<", .close = ">>"),
    filter(skills_formatted, group == !!group)$skills,
    "\n\n\n"
  )
}
```

# Education
```{r education, results = "asis"}
# Merge joint PhD entries
education %>%
  arrange(desc(end), desc(begin)) %>%
  mutate(what = degree,
         when = year(end),
         with = university,
         where = glue("{city}, {region}"),
         why = honors) %>% 
  select(what, when, with, where, why) %>% 
  group_by(what, when) %>% 
  summarize(what = nth(what, 1),
            when = nth(when, 1),
            with = nth(with, 1),
            why = case_when(
              n() == 4 ~ glue("{nth(why, 1)} \\newline {nth(why, 2)} \\newline {nth(why, 3)} \\newline {nth(why, 4)}"),
              n() == 3 ~ glue("{nth(why, 1)} \\newline {nth(why, 2)} \\newline {nth(why, 3)}"),
              n() == 2 ~ glue("{nth(why, 1)} \\newline {nth(why, 2)}"), 
              TRUE ~ nth(why, 1)),
            .groups = "drop") %>% 
  arrange(desc(when)) %>% 
  detailed_entries(
    what,
    when,
    with,
    why,
    .protect = F
  )
```

# Experience

```{r experience}
job.titles |> 
  # Only 5 most recent jobs
  arrange(desc(jobId)) |> 
  #filter(year(begin) >= 2010) |> 
  # Join job descriptions
  left_join(job.descriptions) |> 
  # Format as detailed entries
  detailed_entries(
    what = position,
    when = as.character(
      glue("{year(begin)}-{sprintf('%02d',month(begin, label = FALSE))} -- \n
           {if_else(!is.na(end), 
           paste0(year(end), '-', {sprintf('%02d',month(end, label = FALSE))}), 'present')}")),
    with = employer,
    where = glue("{city}, {region}"),
    why = accomplishments)
```

# Professional Activities and Service

```{r service}
service.titles |> 
  # Only 5 most recent jobs
  arrange(desc(begin)) |> 
  #filter(year(begin) >= 2010) |> 
  # Join job descriptions
  left_join(service.descriptions) |> 
  # Arrange by descending begin date
  arrange(desc(begin), projectId) |> 
  # Format as detailed entries
  detailed_entries(
    what = role,
    when = as.character(
      glue("{year(begin)}-{sprintf('%02d',month(begin, label = FALSE))} -- \n
           {if_else(!is.na(end), 
           paste0(year(end), '-', {sprintf('%02d',month(end, label = FALSE))}), 'present')}")),
    with = group,
    where = if_else(is.na(city), "", as.character(glue("{city}, {region}"))),
    why = description)
```



# Publications

```{r}
bibliography_entries("publications.bib") 
```

# Presentations

*Note:* $\ast$ denotes conference talks and $\dagger$ denotes poster presentation

```{r}
bibliography_entries("presentations.bib") |>
  arrange(desc(issued))
```

\fancyfoot[LO,LE]{\footnotesize This CV was generated on `r Sys.time()`.}